//
//  SuggestedPrompts.swift
//  visibl
//
//  Copyright (c) 2025 Visibl Holdings Limited
//

import Foundation

let suggestedPrompts = [
    "Noir Style, make it black and white. Scenes must be dark and mysterious",
    "Medieval, gothic architecture, dark and imposing, characters in medieval attire",
    "Miami Retro 80s Vibe, vibrant colors and nostalgia",
    "Arabic Nights, inspired by the tales of 1001 Nights",
    "Steampunk-Inspired Style",
    "Cyberpunk Aesthetic, futuristic and neon-lit",
    "Art Nouveau, elegant curves and nature-inspired motifs",
    "Post-apocalyptic Wasteland, ruined cityscapes and survival gear",
    "Underwater Atlantis, bioluminescent creatures and ancient ruins",
    "Wild West Frontier, dusty towns and rugged landscapes",
    "Fairy Tale Whimsy, enchanted forests and magical creatures",
    "Ancient Egyptian, pyramids and hieroglyphics",
    "Film Noir Detective, fedoras and rain-slicked streets",
    "Retro Futurism, 1950s vision of the future",
    "Cosmic Horror, Lovecraftian entities and impossible geometry",
    "Neon Tokyo, bustling streets and towering skyscrapers",
    "Victorian London, foggy streets and gas lamps",
    "Aztec Empire, golden temples and vibrant markets",
    "Superhero Comic Book Style, bold colors and dynamic poses",
    "Art Deco Glamour, geometric patterns and luxurious materials",
    "Solarpunk Utopia, sustainable technology and lush greenery",
    "Impressionist Painting, soft brushstrokes and light effects",
    "Pixel Art, 8-bit nostalgia and blocky characters",
    "Biomechanical, fusion of organic and mechanical forms",
    "Watercolor Dreams, soft washes and ethereal landscapes",
    "Dieselpunk, retro-futuristic machinery and gritty atmosphere",
    "Baroque Opera, opulent stages and dramatic costumes",
    "Surreal Dreamscape, bizarre imagery and floating forms",
    "Futuristic Dystopia, neon decay and ruined cityscapes",
    "Celestial Voyage, cosmic vistas and starry realms",
    "Ancient Norse, rugged fjords and Viking lore",
    "Zen Serenity, minimalist gardens and calm waters",
    "Enchanted Carnival, whimsical rides and vibrant hues",
    "Renaissance Revival, classic art with modern twist",
    "Gothic Horror, eerie mansions and ghostly figures",
    "Cyber Samurai, tradition meets futuristic edge",
    "Mystic Underworld, shadowed alleys and hidden secrets",
    "Digital Mirage, pixel visions and retro futurism",
    "Bioluminescent Jungle, glowing flora and mystic nights",
    "Celtic Legends, ancient stones and misty highlands",
    "Steampunk City, brass gears and industrial charm",
    "Virtual Wonderland, digital realms and neon grids",
    "Cosmic Alchemy, mystical forces and astral symbols",
    "Secret Library, endless tomes and arcane whispers",
    "Frost Kingdom, icy castles and shimmering auroras",
    "Dream City, futuristic skylines and hovering structures",
    "Twilight Forest, enchanted trees and soft moonlight",
    "Nature Reborn, urban ruins reclaimed by greenery",
    "Star Opera, epic starships and cosmic battles",
    "Masked Ball, elegant masquerade and mysterious allure",
    "Ghost Parade, spectral floats and eerie lanterns",
    "Ancient Maya, jungle ruins and vibrant hieroglyphs",
    "Comic Book Hero, dynamic poses and bold colors",
    "Retro Sci-Fi, vintage lasers and cosmic adventures",
    "80s Action, neon vibes and explosive scenes",
    "Cyber Anime, futuristic cities and stylized characters",
    "Space Opera, epic starship battles and stellar vistas",
    "Mystery Thriller, shadowed detectives and urban secrets",
    "Pop Art Explosion, vibrant hues and iconic imagery",
    "Futuristic Brawler, dystopian streets and high-octane combat",
    "Anime Mecha, giant robots and dynamic action",
    "Supernatural Mystery, eerie apparitions and hidden lore",
    "Retro Arcade, pixel art and neon glow",
    "Gritty Urban Legend, street heroes and dark alleys",
    "Fantasy Epic, enchanted realms and daring quests",
    "Modern Samurai, sleek armor and urban landscapes",
    "Galactic Quest, interstellar voyages and alien worlds",
    "Rock 'n' Roll Rebel, electric energy and bold style",
    "Time Travel, swirling eras and retro-future mashup",
    "Paranormal Detective, ghostly cases and moody vibes",
    "Virtual Reality, digital realms and hyper-stylized effects",
    "Martial Arts Master, fluid motion and dynamic combat",
    "Steampunk Rebel, clockwork gadgets and gritty defiance",
    "Urban Sci-Fi, futuristic skylines and high-tech flair",
    "Epic Fantasy, legendary battles and mystical creatures",
    "Cyberpunk Rebel, neon-lit streets and antihero edge",
    "Pop Mashup, eclectic icons and vibrant references",
    "Digital Dream, surreal tech and vivid cyber landscapes"
]
